#!/bin/bash

# The version of duplicity in the EL repo can be way too old.
# [ Currently, the EPEL version is OK - Check this with `yum info duplicity`. ]
#
# This script installs the latest duplicity, including dependencies.
# This script has been tested on Centos 7.
# Just run it as root, sit back and enjoy:
#   wget https://raw.githubusercontent.com/onnozweers/scripts/master/install-duplicity
#   chmod 700 install-duplicity 
#   ./install-duplicity 

# Changelog:
# 2016-10-17 - First version - Onno
# 2016-11-04 - Added yum install wget (it's not in Minimal)
# 2016-11-09 - Added python-paramiko - Onno
# 2016-11-12 - Added rsync, python-crypto, python-boto - Onno
# 2017-05-24 - Added python-swiftclient and python-keystoneclient - Onno
# 2017-07-25 - Added python-fasteners - Onno
# 2017-07-25 - Pick the top tarball, assuming it's the newest (because sorting doesn't always work) - Onno
# 2017-07-25 - Show installed version - Onno
# 2017-12-19 - Added python-urllib3 python-requests to try and prevent https://ask.openstack.org/en/question/110437/importerror-cannot-import-name-unrewindablebodyerror/ - Onno

# For package details see http://duplicity.nongnu.org/duplicity.1.html#sect30 (Requirements section)
yum -y install wget gcc rsync \
               python-devel python-pip librsync-devel python-lockfile \
               python-paramiko python-crypto python-boto python-fasteners \
               python-urllib3 python-requests
pip install --upgrade PyDrive python-swiftclient python-keystoneclient

# Prepare dir
cd
mkdir -p duplicity
cd duplicity

# Clean up previous stuff
rm -rf /root/duplicity/*

# Find the latest duplicity source tarball from Launchpad.
latest=$(wget https://code.launchpad.net/duplicity/+download -o /dev/null -O - \
         | egrep -o 'https://code.launchpad.net/duplicity/[-0-9a-z\./]+/\+download/duplicity-[-0-9a-z\.]+.tar.gz' \
         | head -n 1)
wget "$latest" -O duplicity.tar.gz
tar -xf duplicity.tar.gz
cd duplicity*/
python setup.py install

echo
echo 'Running `duplicity --version`:'
duplicity --version
